name: domain-llm-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # 基础依赖
  - pip
  - numpy>=1.21.4
  - pandas>=1.3.4
  # 可视化
  - matplotlib>=3.5.0
  - seaborn>=0.11.2
  # 数据处理
  - nltk>=3.6.5
  - beautifulsoup4>=4.10.0
  - requests>=2.26.0
  - tqdm>=4.62.3
  - regex>=2021.11.10
  # 评估
  - scikit-learn>=1.0.1
  # 工具
  - pyyaml>=6.0
  # 通过pip安装的依赖
  - pip:
    - transformers>=4.20.0
    - datasets>=2.0.0
    - accelerate>=0.12.0
    - sentencepiece>=0.1.96
    - tokenizers>=0.12.1
    - rouge>=1.0.1
    - sacrebleu>=2.0.0
    - fastapi>=0.70.0
    - uvicorn>=0.15.0
    - pydantic>=1.8.2
    - jsonlines>=2.0.0
